packages:
  - apps/*
  - packages/*
  - adapters/*

allowBuilds:
  esbuild: true
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - tsx@4.23.10
  - '@aws-sdk/client-s3@3.1105.0'
  - '@aws-sdk/s3-request-presigner@3.1105.0'
  - lucide-react@1.30.0
